### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MetaLex'

### ISSUE THREAD

**Issue by billmetangmo** [Levis0045/MetaLex-vagrant#10]
I got this error on ubuntu xenial when exceuting fileTestMetaLex.py

ubuntu@ubuntu-xenial:/vagrant$ python fileTestMetaLex.py
Traceback (most recent call last):
  File "fileTestMetaLex.py", line 31, in <module>
    images  = project.MetaLex.getImages(imagelist)
  File "/vagrant/MetaLex/dicOcrText/normalizeImage.py", line 55, in getImages
    imageroot, ext = MetaLex.MetaLex.dicProject.get_part_file(image)
AttributeError: 'module' object has no attribute 'MetaLex'

**Comment by Levis0045** [comment]
Thank Bill! I just fix it !
