### ISSUE TITLE
IOError: [Errno 71] Protocol error: u'MetaLex_projectName_Oct-14-17:57:19-UTC-2017\n.dicLog'

### ISSUE THREAD

**Issue by billmetangmo** [Levis0045/MetaLex-vagrant#33]
when I execute error : "python runMetaLex.py -d 'imagesInput' -s" , i got the error : 

**Traceback (most recent call last):
  File "runMetaLex.py", line 218, in <module>
    run_MetaLex_test()
  File "runMetaLex.py", line 160, in run_MetaLex_test
    dico.dicLog.manageLog.writelog(message, typ='warm')
  File "../MetaLex/dicLog/manageLog.py", line 125, in writelog
  File "../MetaLex/dicLog/manageLog.py", line 114, in folderlog
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 71] Protocol error: u'MetaLex_projectName_Oct-14-17:57:19-UTC-2017\n.dicLog'**

> The folder  MetaLex_MetaLex_projectName/dicLogs/ is created but it's empty.

**Comment by Levis0045** [comment]
helllo Bill !

The problem probably cames from date format in the OS vagrant environment. I just fix it  !
**MetaLex.dicLog.manageLog.getDate()**
`    if re.search(ur'.+\(UTC+.*', datefile) :
        try :
            datetab  = datefile.split(',')[0].split(' ')
            for date in datetab[1:] :
                strdate += date+'-'
            date = unicode(strdate.strip('-').translate(maketrans('û', 'u ')))
            date = unicodedata.normalize('NFKD', date).encode('ascii','ignore')
            return date
        except :
            datetab  = datefile.split(' ')
            for date in datetab :
                strdate += date+'-'
            date = unicode(strdate.strip('-'))
            return date
    else :
        datetab = datefile.split(' ')
        day, month, year = datetab[2], datetab[1], datetab[5]
        strdate = day+'-'+month+'-'+year
        return strdate`

Thank !

**Comment by billmetangmo** [comment]
I got the same error. 
To resolve the issue, I have to copy Metalex-Vagrant directory in Linux based directory like: /home/ubuntu.
Maybe the issue is related to Windows.

**Comment by Levis0045** [comment]
Hello Bill!

Get the last update of metalex to resolve this problem.
